version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: python:3.9
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/mydatabase
      - FLASK_PORT=4000
    depends_on:
      - mongo_db
          

  # flask_app2:
  #   container_name: flask_app2
  #   image: python:3.9
  #   build: .
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "4001:4001"
  #   environment:
  #     - MONGO_URI=mongodb://mongo_db:27017/mydatabase
  #     - FLASK_PORT=4001
  #   depends_on:
  #     - mongo_db
    

  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - "27017:27017"
          
  redis:
    image: redis
    ports:
      - "6379:6379"

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - flask_app
  #     - flask_app2
      